---
PRINT_ALPACA: false
EMAIL_REPORTER: false
APPLY_FIXES: all

# Lint specifig settings
ENABLE: [MARKDOWN, YAML, COPYPASTE]

COPYPASTE_JSCPD_ARGUMENTS: --ignore "**/report/**","LICENSES" --threshold "10"
